server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka-svc:8761/eureka/
zuul:
  routes:
    provider: /p/**
    Consumer: /c/**